# Generated by Django 6.0.6 on 2026-07-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome do Atleta')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Rodada')),
                ('sets_a', models.IntegerField(default=0, verbose_name='Sets Atleta A')),
                ('sets_b', models.IntegerField(default=0, verbose_name='Sets Atleta B')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Finalizado'), ('cancelled', 'Não Ocorreu (Cancelado)')], default='pending', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.category')),
                ('player_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='tournaments.player')),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='tournaments.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.player')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['round_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Jogos')),
                ('wins', models.IntegerField(default=0, verbose_name='Vitórias')),
                ('losses', models.IntegerField(default=0, verbose_name='Derrotas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.category')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.player')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['-points', '-wins', 'matches_played'],
                'unique_together': {('category', 'player')},
            },
        ),
    ]
