# Generated by Django 6.0.6 on 2026-07-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(verbose_name='Rodada Atual')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo (Exibir no site)')),
            ],
            options={
                'verbose_name': 'Banner da Home',
                'verbose_name_plural': 'Banners da Home',
            },
        ),
    ]
