# Generated by Django 6.0.6 on 2026-07-05 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Barragem')),
                ('current_round', models.IntegerField(default=1, verbose_name='Rodada Atual')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo (Exibir no site)')),
            ],
            options={
                'verbose_name': 'Barragem',
                'verbose_name_plural': 'Barragens',
            },
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Categoria'),
        ),
        migrations.AddField(
            model_name='category',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tournament', 'name')},
        ),
    ]
