# Generated by Django 6.0.6 on 2026-07-06 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_delete_homebanner_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutTournament',
            fields=[
            ],
            options={
                'verbose_name': 'Torneio Eliminatório',
                'verbose_name_plural': 'Torneios Eliminatórios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tournaments.tournament',),
        ),
        migrations.CreateModel(
            name='RankingTournament',
            fields=[
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tournaments.tournament',),
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Torneio/Ranking Base', 'verbose_name_plural': 'Torneios/Rankings Base'},
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournaments.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='match',
            name='position_in_bracket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='set1_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 1 - A'),
        ),
        migrations.AddField(
            model_name='match',
            name='set1_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 1 - B'),
        ),
        migrations.AddField(
            model_name='match',
            name='set2_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 2 - A'),
        ),
        migrations.AddField(
            model_name='match',
            name='set2_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 2 - B'),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 3 - A'),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 3 - B'),
        ),
        migrations.AddField(
            model_name='match',
            name='set4_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 4 - A'),
        ),
        migrations.AddField(
            model_name='match',
            name='set4_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 4 - B'),
        ),
        migrations.AddField(
            model_name='match',
            name='set5_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 5 - A'),
        ),
        migrations.AddField(
            model_name='match',
            name='set5_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 5 - B'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_matches', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='competition_type',
            field=models.CharField(choices=[('simples', 'Simples'), ('duplas', 'Duplas')], default='simples', max_length=20, verbose_name='Competição'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='set_format',
            field=models.CharField(choices=[('3_normal', 'Melhor de 3 Sets Normal'), ('3_super', 'Melhor de 3 Sets (3º Set é Super Tiebreak)'), ('5_normal', 'Melhor de 5 Sets Normal')], default='3_normal', max_length=20, verbose_name='Formato de Sets'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('ranking', 'Ranking'), ('knockout', 'Torneio Eliminatório')], default='ranking', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.category'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sets_a',
            field=models.IntegerField(default=0, verbose_name='Sets Ganhos (A)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sets_b',
            field=models.IntegerField(default=0, verbose_name='Sets Ganhos (B)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Torneio/Ranking'),
        ),
    ]
