# Generated by Django 6.0.6 on 2026-07-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_knockouttournament_rankingtournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_of_brackets',
            field=models.IntegerField(default=1, help_text='Apenas para Torneios Eliminatórios: O número de chaves paralelas (ex: 2 para dividir 32 atletas em 2 chaves de 16).', verbose_name='Número de Chaves (Eliminatório)'),
        ),
    ]
