# Generated by Django 6.0.6 on 2026-07-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_number_of_brackets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Marque esta opção quando o torneio/ranking chegar ao fim.', verbose_name='Encerrado'),
        ),
    ]
