# Generated by Django 6.0.6 on 2026-07-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_finished',
            field=models.BooleanField(default=False, help_text='Se todas as categorias forem encerradas, o ranking também será.', verbose_name='Encerrada'),
        ),
    ]
