# Generated by Django 6.0.6 on 2026-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_category_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='sets_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sets Ganhos (A)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sets_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sets Ganhos (B)'),
        ),
    ]
