# Generated by Django 6.0.6 on 2026-07-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_match_sets_a_alter_match_sets_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Jogo no YouTube'),
        ),
    ]
