# Generated by Django 6.0.6 on 2026-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_match_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='points_loser_2x0',
            field=models.IntegerField(default=0, help_text='Pontos recebidos pelo perdedor de um jogo 2x0.', verbose_name='Pontos (Derrota 2x0)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_loser_2x1',
            field=models.IntegerField(default=1, help_text='Pontos recebidos pelo perdedor de um jogo 2x1.', verbose_name='Pontos (Derrota 2x1)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_winner_2x0',
            field=models.IntegerField(default=3, help_text='Pontos recebidos pelo vencedor de um jogo 2x0.', verbose_name='Pontos (Vitória 2x0)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_winner_2x1',
            field=models.IntegerField(default=2, help_text='Pontos recebidos pelo vencedor de um jogo 2x1.', verbose_name='Pontos (Vitória 2x1)'),
        ),
    ]
