# Generated by Django 6.0.6 on 2026-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournament_points_loser_2x0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#050B14', help_text='Ex: #050B14', max_length=20, verbose_name='Cor de Fundo Principal')),
                ('primary_color', models.CharField(default='#00d2ff', help_text='Ex: #00d2ff', max_length=20, verbose_name='Cor Principal (Destaque)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
