# Generated by Django 6.0.6 on 2026-09-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='subtitle_color',
            field=models.CharField(default='#94A3B8', help_text='Cor do texto abaixo do título principal', max_length=20, verbose_name='Cor do Subtítulo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='title_color',
            field=models.CharField(default='#FFFFFF', help_text='Cor do título principal nas páginas', max_length=20, verbose_name='Cor do Título'),
        ),
    ]
