# Generated by Django 6.0.6 on 2026-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_siteconfiguration_subtitle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='overlay_color',
            field=models.CharField(default='#000000', help_text='Cor da camada que fica por cima da imagem de fundo', max_length=20, verbose_name='Cor da Camada Fumê (Overlay)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='overlay_opacity',
            field=models.IntegerField(default=60, help_text='0 (Totalmente transparente) a 100 (Totalmente sólido)', verbose_name='Opacidade do Fumê (%)'),
        ),
    ]
