# Generated by Django 6.0.6 on 2026-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_siteconfiguration_overlay_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='watermark_image',
            field=models.ImageField(blank=True, help_text='Imagem para ficar no canto inferior direito', null=True, upload_to='backgrounds/', verbose_name="Imagem de Marca d'Água"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='watermark_opacity',
            field=models.IntegerField(default=15, help_text='0 (Invisível) a 100 (Totalmente opaca, padrão: 15)', verbose_name="Opacidade da Marca d'Água (%)"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='watermark_size',
            field=models.IntegerField(default=450, help_text='Tamanho em pixels (padrão: 450)', verbose_name="Tamanho da Marca d'Água (px)"),
        ),
    ]
