# Generated by Django 6.0.6 on 2026-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_siteconfiguration_watermark_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='watermark_bottom',
            field=models.IntegerField(default=-20, help_text="Distância do fundo da tela. Use números negativos (ex: -50) para empurrar a imagem mais para baixo caso os pés estejam 'voando'.", verbose_name='Posição Vertical (px)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='watermark_right',
            field=models.IntegerField(default=-20, help_text='Distância da direita. Use números negativos para empurrar mais para a direita.', verbose_name='Posição Horizontal (px)'),
        ),
    ]
