# Generated by Django 6.0.6 on 2026-09-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_siteconfiguration_watermark_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='watermark_rotation',
            field=models.IntegerField(default=-5, help_text='Giro da imagem. Padrão: -5. Zero para deixar reto.', verbose_name='Rotação (graus)'),
        ),
    ]
